# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c91ee6f6b93df0b1a67092aee6af6a2c9e1ab65615264eeb90e9ad37cba3a6b99612f3e0dbe8cfeb780dcd9e35c6007cd7571e56da910294ae3afbad1d1e659f

test:
  secret_key_base: 0756e3dde4984efc87d09ab938406e4a23b063dcf274c419a0651b09d841cfa91aed14c7197fdf517321079cdea02eb51abd68341ad367d9f04e7eced1da793d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
