# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b87d6375613894460f437ff787298339b5f403ae9dbed95cb2fff21b5fbf82df4539f613a2d5cd529948eaadb696394b036ec67b7642e4b70521e2d0376870e

test:
  secret_key_base: 019470a7eea56b783a2511aad643847e2c455dae47c73aba7eaf06659a9c6c1ae9e943a4245f2eeedb212361b9e0901f8922cdd98bb475963bea520b16cde187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
